plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Max: 20

RSpec/MultipleDescribes:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
