plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Max: 20

RSpec/MultipleDescribes:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/contract/**/*
    - spec/integration/**/*

RSpec/IteratedExpectation:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
